package interviewSeries;

public class Series1 
{
	/**
	 * What is selenium.
	 *	Does selenium support automation of pages made in PHP and HTML.
	 *	Does selenium support automation of application made in only in java.
	 *	Does selenium support desktop application automation.
	 *	Does selenium has execution engine.
	 *	Does selenium has excel reading methods.
	 * What is component of selenium?
	 * What are the different types of locator in selenium?
	 * what is selenium Grid.
	 */
	
	
	/**
	 What are the lemitation of Selenium?
	 
	  Selenium supports testing of only WebBased Application
	  Mobile application cannot be test by using selenium
	  capcha code and bar code reader cannot be tested by selenium.
	  report can only be generated by only third party tool like testng and junit.
	   
	 */
	/**
	 different types of locator in selenium?
	 1.ID
	 2.ClassName
	 3.Name
	 4.TagName
	 5.LinkTest
	 6.PartialLinkText
	 7.Xpath
	 8.css Selector
	 
	 */

}
